### ISSUE TITLE
Block producers from exemplary topologies (small and large) crashing

### ISSUE THREAD

**Issue by piotr-iohk** [MinaFoundation/minimina#52]
## Problem
It seems that all block producers from our [large_network](https://github.com/MinaFoundation/minimina/tree/main/tests/data/large_network) and [small_network](https://github.com/MinaFoundation/minimina/tree/main/tests/data/small_network) crash after few minutes from starting

The error is:
```
{"timestamp":"2023-09-13 13:01:49.941934Z",
"level":"Fatal",
"source":{"module":"Consensus__Proof_of_stake","location":"File \"src/lib/consensus/proof_of_stake.ml\", line 3105, characters 12-24"},
"message":"An empty epoch is detected! This could be caused by the following reasons: system time is out of sync with protocol state time; or internet connection is down or unstable If it is the first case, please setup NTP. If it is the second case, please check the internet connection.",
"metadata":{"host":"193.164.254.212","peer_id":"12D3KooWPct9Lcb7VAnooskBUQDRU4Bv9asGiUjpRwWTKh2n1T4y","port":7077}}
```

Note that there is no issue when starting default network created with `minimina network create`.

### Steps to reproduce:
1. Create network (either small or large)
```
minimina network create \
-t tests/data/small_network/topology.json \
-g tests/data/small_network/genesis_ledger.json \
-n small
```
2. Start network

```
minimina network start -n small
```

3. Monitor status of the network until you see some block producer nodes have exited state.
```
minimina network status -n small | jq .services[].state
```

4. Check the logs of exited service

```
docker logs receiver-small
```

## Tasks
- [ ] Documentation/README to reflect the changes
- [x] Check genesis timestamp on `network start`, if too old, warn and exit
- [x] Overwrite the genesis timestamp to now on `network create`
