### ISSUE TITLE
Performance regression testing in CI

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/minimina#59]
## Problem

I apparently like to introduce performance regressions 😅

## Acceptance Criteria

Choose some reasonable tolerance for performance regressions and test as part of CI pipeline.

## Tasks
- [ ] Choose reasonable tolerance for various operations
- [ ] Trigger errors/warnings when thresholds are violated
- [ ] Implement in CI pipeline
